### ISSUE TITLE
Sugestões

### ISSUE THREAD

**Issue by zBlackGamer1** [SOekd/MiyukiSystem#1]
- TPA com Json
- Anúncios automático com Json
- Vanish com mensagem na action bar (enquanto estiver ativo)

**Comment by mattnicee7** [comment]
Opa, esses comandos com mensagem em  json irão ter já e serão totalmente configuráveis.
O vanish irá ter sim, mas talvez não com essa mensagem na action-bar, será pensado ainda.

Obrigado pela sugestão :)
